### ISSUE TITLE
release 2.0.10 versioning

### ISSUE THREAD

**Issue by mrgleeco** [mozilla/sops#240] opened 2017-08-26 06:53 UTC
thanks for the new version!  govcloud works!!
but version did not get the bump(?)
lat https://github.com/mozilla/sops/blob/master/cmd/sops/version.go#L13

This is reporting from deb install:

```
||/ Name                             Version                           Architecture Description
+++-================================-=================================-============-===================================================================================================================
ii  sops                             2.0.10                            amd64        Sops is an editor of encrypted files that supports YAML, JSON and BINARY formats and encrypts with AWS KMS and PGP.

$ dpkg-query -L sops
/.
/usr
/usr/local
/usr/local/bin
/usr/local/bin/sops
/usr/share
/usr/share/doc
/usr/share/doc/sops
/usr/share/doc/sops/changelog.gz

$ /usr/local/bin/sops -v
sops 2.0.9 (latest)
```

**Comment by autrilla** [comment] 2017-08-26 06:54
Duplicate of #237

**Closed by autrilla** 2017-08-26 06:54 UTC
