### ISSUE TITLE
sops not correct decrypt json files.

### ISSUE THREAD

**Issue by ultramozg** [mozilla/sops#740] opened 2020-09-15 13:40 UTC
Hello, 
sorry I've unable to find similar issue. I use `sops` cli utility on Ubuntu 18.04, `.sops.yaml` config 

installed packages:
```file
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-================================================================================
ii  sops                                  3.6.1                   amd64                   Sops is an editor of encrypted files that supports YAML, JSON and BINARY formats
ii  vim                                   2:8.0.1453-1ubuntu1.3   amd64                   Vi IMproved - enhanced vi editor
```

```file
creation_rules:
  - path_regex: vault/*
    key_groups:
    - pgp:
      - 8D4B92C99491D5E50954F87DC4051BE5D8B4BA75
      ***
```

I've encrypted some vault and after that sops unable to decrypt this vault correctly.

For example i create `t.json` with the following content
```file
{
  "password": ".7G%Jh%]Z8h3r<>L"
}
```

after that i try to decrypt content

```file
sops -d vault/t.json
{
        "password": ".7G%Jh%]Z8h3r\u003c\u003eL"
}
```

Maybe I did something wrong.

**Comment by felixfontein** [comment] 2020-09-25 13:54
The decrypted JSON looks like it is semantically equivalent to the original one.

**Comment by ultramozg** [comment] 2020-09-25 14:03
yes indeed I was able to decrypt without issues this vault


```file
sops exec-file vault/test/t.json 'cat {}'
{
        "id": "test_vault",
        "attributes": {
                "passowrd": ".7G%Jh%]Z8h3r\u003c\u003eL"
        }
}

sops exec-file vault/test/t.json 'knife vault create test test_vault -J {}'

knife vault show test test_vault
{
  "id": "test_vault",
  "attributes": {
    "passowrd": ".7G%Jh%]Z8h3r<>L"
  }
}
```

However it's very strange that sops it's displays some symbols with unicode encoding  '<>' -> '\u003c\u003'.

**Comment by autrilla** [comment] 2020-09-25 14:22
Duplicate of #464

**Closed by autrilla** 2020-09-25 14:22 UTC
