### ISSUE TITLE
Ability to support IgnoreMAC for the external decrypt API 

### ISSUE THREAD

**Issue by domhdp** [mozilla/sops#783] opened 2020-12-08 00:47 UTC
Hi!

I noticed that the external decrypt API does not have an option like `IgnoreMAC`, would this be something that you'd be open to having incorporated?

This would be useful for other projects leveraging SOPS for encryption (eg. https://github.com/isindir/sops-secrets-operator#known-issues)

**Comment by felixfontein** [comment] 2020-12-08 06:09
See #758.

**Comment by autrilla** [comment] 2020-12-08 08:55
Closing as dupe of #758.

**Closed by autrilla** 2020-12-08 08:55 UTC
