### ISSUE TITLE
sops3 destroys my terminal

### ISSUE THREAD

**Issue by mxxcon** [mozilla/sops#273] opened 2017-10-25 14:32 UTC
I have a simple command which I use to sort content of my encrypted files
`sops -d file.json |jq -S . |pbcopy |sops file.json`
With sops 1 and 2 it worked perfectly fine.
With sops 3 it destroys my terminal. My text editor doesn't stay open, instead I get returned into a busted terminal. Nothing that I can type is visible. ctrl-c/ctrl-d do not work. All colors are mixed up.
This is what my terminal looks like after running that command.
<img width="809" alt="screen shot 2017-10-25 at 10 31 18 am" src="https://user-images.githubusercontent.com/847140/32004397-ae4ea528-b96f-11e7-9a18-bb443c632f3c.png">

I'm running latest version of OSX 10.13.
Sops was installed using brew
```
: sops --version
sops 3.0.0 (latest)
```

**Comment by autrilla** [comment] 2017-10-25 16:55
Your command works for me on macOS using Terminal.app and zsh. I don't see any weird output and my terminal is in a normal state after executing it. Can you provide more details about your environment so we can track down the cause? It seems that your editor is erroring out for some reason.

Either way, when something like this happens, usually typing `reset` and hitting return fixes terminals. As another note, perhaps the misbehavior is due to piping stuff into sops unexpectedly -- `pbcopy` shouldn't output anything anyway, and `sops` doesn't expect anything on stdin; but I'm not sure what exactly you're trying to achieve with this pipeline.

**Comment by mxxcon** [comment] 2017-10-25 17:18
I'm using bash in iterm2.
My editor is `mcedit`, part of midnight commander, also installed thought _brew_.

Yes, logically I should replace last `|` with `&&` since I'm not piping from pbcopy into sops.
Still it didn't explode like that before in sops1/2. 🤔
`reset` only partly fixes things. I still can't ctrl-c or ctrl-d and can't use mouse to scroll up in the buffer and i suspect there are other things still broken i haven't trired.

**Comment by autrilla** [comment] 2017-10-25 17:37
I managed to reproduce it with SOPS 3. This seems like a but in mcedit. I just tried with sops 2.0.9 and the same thing happens.

```
sops2.0.9 --version                                                                                                                                     
sops 2.0.9
[info] sops 3.0.0 is available, update with `go get -u go.mozilla.org/sops/cmd/sops`
❯ sops2.0.9 -d file.json |jq -S . |pbcopy |sops2.0.9 file.json 
```

And I get the same garbled output.

Running

```
❯ true | mcedit file.json
```

Results in the same thing. I don't think this is an issue with SOPS.

**Comment by autrilla** [comment] 2017-10-26 11:17
I'm closing this, reopen if you still think this is an issue with SOPS.

**Closed by autrilla** 2017-10-26 11:17 UTC
