### ISSUE TITLE
Error encrypting tree: Error walking tree: Cannot walk value, unknown type: <nil>

### ISSUE THREAD

**Issue by jeffrichiefs** [mozilla/sops#249] opened 2017-09-14 15:38 UTC
```
[jrichie@jrichie-MBP] : ~/workspace/infrastructure-dev ✕  sops -e -i values.yaml 
Error encrypting tree: Error walking tree: Cannot walk value, unknown type: <nil>
[jrichie@jrichie-MBP] : ~/workspace/infrastructure-dev ✕
```

**Comment by autrilla** [comment] 2017-09-14 15:39
Closing as this is a duplicate of #171

**Closed by autrilla** 2017-09-14 15:39 UTC
