### ISSUE TITLE
Encrypting a dotenv file

### ISSUE THREAD

**Issue by azoom-y-ishii** [mozilla/sops#404] opened 2018-12-06 01:39 UTC
Hi,

When I encrypt a dotenv file, sops shows an error.

```
$ export SOPS_GCP_KMS_IDS="/my/gcp/kms/id"
$ echo "MY_SECRET=IAMNOOBIE" > .env
$ sops -e --input-type dotenv .env > .env.enc
$ sops -d --input-type dotenv .env.enc
Error dumping file: No binary data found in tree
```

Curiously when I change the --input-type option to 'binary', sops tries to decrypt the file as json

```
sops -d --input-type binary .env.enc
Error unmarshalling input json: invalid character 'M' looking for beginning of value
```

This is content of .env.enc file encrypted above
```
MY_SECRET=ENC[AES256_GCM,data:fPXbWqbBIQAf,iv:95P4nbiXqKFMi40BJ9qxJwvJsFsxwUX8+4zTWmb3f2A=,tag:hSno4msgkoni4pjztj9pcA==,type:str]
sops_gcp_kms__list_0__map_resource_id=/my/gcp/kms/id
sops_unencrypted_suffix=_unencrypted
sops_version=3.2.0
sops_gcp_kms__list_0__map_created_at=2018-12-06T01:20:04Z
sops_gcp_kms__list_0__map_enc=CiQAIi6/oQO4xkjucL5skKD78BVHZc/XkGfknW632V6hsw5zf7cSSQCu3Rngla2XUV787oP0E6cV467DS76xifsDSHJpe2FGKxCmv8Px4c7Qy5Qx+p5+JxCUUDkZvPKln5m1BTxz5ZqH4nB3upY4UwI=
sops_lastmodified=2018-12-06T01:20:04Z
sops_mac=ENC[AES256_GCM,data:hQlyTUr6x/c7Wfamx3Ore00iB7oyZch086GI2yZlKU6UtwL93gjR4RxIAKlawbobRsc8+kBAvXeD//U3wOtBFdfEsQHrpNTF3xpSy5W18OjXM2DztrOoWOlIBSfqgr2cIXNlUjVB8Qk3usPq1Dqwp3skw68SI8hhTy6cfvg0Tsc=,iv:y5HAe2x4kCdv2bfKVdVixFvBAw7YxnIrsK2Waik0xg8=,tag:16zfexV72D94knL5ZZpeaQ==,type:str]
```

My sops version is sops 3.2.0, and I use macOS

Something is wrong with my operation?

**Comment by autrilla** [comment] 2018-12-06 15:17
This is a duplicate of #367. When you use the `.enc` suffix on the file name, SOPS assumes the file to be a binary file. Try using `enc.env` as the file name instead, or specify `--input-type dotenv`.

**Closed by autrilla** 2018-12-06 15:17 UTC
