### ISSUE TITLE
Restructure SOPS to be class based

### ISSUE THREAD

**Issue by twolfson** [mozilla/sops#48] opened 2016-02-04 18:36 UTC
The current implementation of SOPS is functionally based. This is good for programs that rely on transforming data. However, it's beginning to get unwieldy with all of the state passing it is doing (e.g. `digest`, `iv`, `key`, and in #47 `unencrypted_suffix`).

I suggest considering a refactor to swap out the core with something more class based so state is always located on `self`. I will create a gist to provide examples of what I mean.

**Comment by jvehent** [comment] 2016-02-04 18:54
This is actually a duplicate of #3, but no one had time to work on it. That said, I agree wholeheartedly, but I'll close as duplicate and move your comment to #3.

**Comment by twolfson** [comment] 2016-02-04 18:55
Ah, sorry. I totally didn't see #3 =(

**Closed** 2016-02-04 18:55 UTC
Labels: duplicate
