### ISSUE TITLE
sops causes yamllint to fail the file checks

### ISSUE THREAD

**Issue by speculatrix** [mozilla/sops#836] opened 2021-03-23 12:37 UTC
when editing a yaml file, sops removes the yaml header line, i.e the "---" line
this then causes yamllint to fail.

sops also gets the indenting wrong, so again, yamllint reports errors.

**Comment by autrilla** [comment] 2021-03-23 12:49
This is a duplicate of many other issues. Please use the search function. We don’t consider this a bug, because there isn’t one single YAML style.

**Closed by autrilla** 2021-03-23 12:49 UTC

**Comment by speculatrix** [comment] 2021-03-23 13:45
ok, I'm happy to go with whatever yaml style, so long as there's some sort of linting tool for that format which works with sops, please can you recommend one?

**Comment by autrilla** [comment] 2021-03-23 14:19
It seems like yamllint has tons of configuration options. I personally don't use any YAML linter.

**Comment by felixfontein** [comment] 2021-03-23 14:23
In particular, yamllint has an `ignore` config option, where you could add something like `*.sops.yaml`. (https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths)

**Comment by speculatrix** [comment] 2021-03-23 14:34
> It seems like yamllint has tons of configuration options. I personally don't use any YAML linter.

ah, who cares about code quality ;-)
